stages:
  - build
  - test
  - deploy_dev
  - deploy_prod
  - finish

variables:
  OWNER_NAME: Mr-p1gnum
  CICD_VERSION: v1.0
  LOG_FILE_NAME: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA.txt

image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

default:
  artifacts:
    paths:
        - $LOG_FILE_NAME


build-job:
  stage: build
  script: 
    - echo "Build Started"
    - echo "Bulding..."> $LOG_FILE_NAME
    - echo "Build completed"

test-job:
  stage: test
  script: 
    - echo "Test Started"
    - echo "Testing...">> $LOG_FILE_NAME
    - echo "Test completed"

test-job2:
  stage: test
  script: 
    - echo "Test2 Started"
    - echo "Testing2...">> $LOG_FILE_NAME
    - echo "Test2 completed"


test-job3:
  stage: test
  needs:
    - test-job2
    - test-job
  script: 
    - echo "Test3 Started"
    - echo "Testing3...">> $LOG_FILE_NAME
    - echo "Test3 completed"


deploy_to_dev_job:
  stage: deploy_dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Deploy Started"
    - echo "Deploying...">> $LOG_FILE_NAME
    - echo "Deploy completed"
    - cat $LOG_FILE_NAME

deploy_to_prod_job:
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - echo "---Deploy to PROD Started---"
    - echo "Deploy to PROD..." >> $LOG_FILE_NAME
    - echo "---Deploy to PROD Completed---"  
    - cat $LOG_FILE_NAME

finish_job:
    stage : finish
    script:
        - echo "---Finish Job Started---"
        - echo "Finish!!!" >> $LOG_FILE_NAME
        - echo "Owner of the Pipeline $CICD_VERSION is $OWNER_NAME" >> $LOG_FILE_NAME
        - cat $LOG_FILE_NAME
        - ls -l
        - echo "---Finish Job Completed---" 