stages:
  - build
  - test
  - deploy_dev
  - deploy_prod


variables:
CI_REGISTRY_IMAGE: todo-app

image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest



build-job:
  stage: build
  script: 
    - echo "Build Started"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - echo "Build completed"

test-job:
  stage: test
  script: 
    - echo "Test Started"
    - echo "Testing...">> $LOG_FILE_NAME
    - echo "Test completed"



deploy_to_dev_job:
  stage: deploy_dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Deploy Started"
    - echo "Deploying...">> $LOG_FILE_NAME
    - echo "Deploy completed"
    - cat $LOG_FILE_NAME

deploy_to_prod_job:
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - echo "---Deploy to PROD Started---"
    - echo "Deploy to PROD..." >> $LOG_FILE_NAME
    - echo "---Deploy to PROD Completed---"  
    - cat $LOG_FILE_NAME
