stages:
  - build
  - test
  - deploy_dev
  - deploy_prod

variables:
  IMAGE: $DOCKERHUB_USERNAME/todo-app:$CI_COMMIT_SHORT_SHA

image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

default:
  artifacts:
    paths:
      - image/

build-job:
  stage: build
  script: 
    - echo "$DOCKER_ACCESS_KEY" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Build Started"
    - docker build . -t $IMAGE 
    - docker push $IMAGE
    - ls -lah
    - echo "Build completed"
    
test-job:
  stage: test
  script: 
    - docker pull $IMAGE
    - docker run --rm -v ./todo-data:/todo-app/data -d -p 80:5000 $IMAGE

deploy_to_dev_job:
  stage: deploy_dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Deploy Started"
    - sleep 10
    - echo "Deploy completed"

deploy_to_prod_job:
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - echo "---Deploy to PROD Started---"
    - echo "Deploy to PROD..." >> $LOG_FILE_NAME
    - echo "---Deploy to PROD Completed---"  
