version: '3.8'

services:
  todo-app:
    image: todo-app:latest
    env_file:
      - ./.env
    ports:
      - '80:5000'
    volumes:
      - ./todo-data:/todo-app/data
    container_name: todo
    restart: 'unless-stopped'