version: '3.8'

services:
  todo-app:
    image: todo-app:latest
    env_file:
      - .env
#    network_mode: host
    ports:
      - '200:5000'
    command: mkdir data
    volumes:
      - ./todo-data:/todo-app/data
    container_name: todo
    restart: 'unless-stopped'